includes:
- src/configs/base.yml

model:
  name: orbnet_native
  emb_size_atom: 128
  emb_size_edge: 64
  cutoff: 6.
  rbf:
    name: spherical_bessel
  envelope:
    name: exponential
  period_and_group_path: 'src/data/features.csv'
  regress_forces: False
  use_pbc: True
  otf_graph: False

optim:
  batch_size: 32
  epochs: 25
  eval_batch_size: 32
  eval_every: 7192
  lr_initial: 0.001
  max_epochs: 25
  max_lr: 0.001
  num_workers: 10
  scheduler: OneCycleLR
  steps_per_epoch: 14385
  ema_decay: 0.999
  